qtbase: drop DEPENDS on virtual/libgl when building without opengl support
* we cannot explicitly disable opengl with -no-opengl, because then it
  fails to build:
  /qtbase-opensource-src-5.0.0/src/platformsupport/eglconvenience/qeglplatformcontext.cpp:62:72: error: 'QPlatformOpenGLContext' has not been declared
  /qtbase-opensource-src-5.0.0/src/platformsupport/eglconvenience/qeglplatformcontext.cpp: In constructor 'QEGLPlatformContext::QEGLPlatformContext(const QSurfaceFormat&, int*, EGLDisplay, EGLenum)':
  /qtbase-opensource-src-5.0.0/src/platformsupport/eglconvenience/qeglplatformcontext.cpp:69:70: error: invalid static_cast from type 'int*' to type 'QEGLPlatformContext*'
  The same with 5.0.2

Signed-off-by: Simon Busch <morphis@gravedo.de>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>